### ISSUE TITLE
2.1.0 can't start in standalone mode

### ISSUE THREAD

**Issue by doublemarket** [browserup/browserup-proxy#263]
**Describe the bug**

With the [2.1.0 zip file](https://github.com/browserup/browserup-proxy/releases/download/v2.1.0/browserup-proxy-2.1.0.zip), browserup-proxy can't start with the following error:

```
$ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

$ uname -a
Darwin MacBook-Pro-2.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

$ cd browserup-proxy-2.1.0/bin

$ ./browserup-proxy
Running BrowserUp Proxy, powered by LittleProxy.
[INFO  2020-05-21T16:06:25,046 com.browserup.bup.proxy.Main] (main) Starting BrowserUp Proxy version ${project.version}
[INFO  2020-05-21T16:06:25,137 org.eclipse.jetty.util.log] (main) Logging initialized @6091ms to org.eclipse.jetty.util.log.Slf4jLog
[INFO  2020-05-21T16:06:25,290 org.eclipse.jetty.server.Server] (main) jetty-9.4.26.v20200117; built: 2020-01-17T12:35:33.676Z; git: 7b38981d25d14afb4a12ff1f2596756144edf695; jvm 1.8.0_77-b03
[INFO  2020-05-21T16:06:25,317 org.eclipse.jetty.server.session] (main) DefaultSessionIdManager workerName=node0
[INFO  2020-05-21T16:06:25,317 org.eclipse.jetty.server.session] (main) No SessionScavenger set, using defaults
[INFO  2020-05-21T16:06:25,320 org.eclipse.jetty.server.session] (main) node0 Scavenging every 660000ms
May 21, 2020 4:06:25 PM org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider io.swagger.v3.jaxrs2.integration.resources.OpenApiResource registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint c
onfiguration problems the provider io.swagger.v3.jaxrs2.integration.resources.OpenApiResource will be ignored.
[INFO  2020-05-21T16:06:26,075 org.hibernate.validator.internal.util.Version] (main) HV000001: Hibernate Validator 6.0.17.Final
May 21, 2020 4:06:26 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: Unknown HK2 failure detected:
MultiException stack 1 of 1
java.lang.NoSuchMethodError: javax.validation.BootstrapConfiguration.getClockProviderClassName()Ljava/lang/String;
```

(refer to the attached [bup.log](https://github.com/browserup/browserup-proxy/files/4661029/bup.log) for the detail)

**To Reproduce**
1. Download the zip
2. Extract it
3. Start by running `./browserup-proxy` in the `bin` directory

**Expected behavior**

It should start without errors.

**Screenshots**

**Please complete the following information:**
 - OS: macOS Catalina with Java 1.8.0_77
 - Browser -
 - Version -

**Additional context**

I also tried with the following environments (all are with [official images on Docker Hub](https://hub.docker.com/_/openjdk)) but on all of them, browserup-proxy doesn't start with the same error:

- Openjdk 11 (`openjdk:11`)
  ```
  # java -version
  openjdk version "11.0.7" 2020-04-14
  OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
  OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode)
  ```
- Openjdk 15 (`openjdk:15`)
  ```
  # java -version
  openjdk version "15-ea" 2020-09-15
  OpenJDK Runtime Environment (build 15-ea+23-1098)
  OpenJDK 64-Bit Server VM (build 15-ea+23-1098, mixed mode, sharing)
  ```

I also tried to create an archive from the code with the tag `v2.1.0` by running `gradlew build --info` but using the archive, browserup-proxy doesn't start with the same error as well.

**Comment by PAVITHRA001** [comment]
Getting the same issue as above

**Comment by thiagotrentin** [comment]
Same issue here, although running on windows environment
Previous version still working fine

**Comment by erickubenka** [comment]
Same issue here.
Not running on windows or linux as well. :(

**Comment by dpowell** [comment]
This should be fixed now for Java 8 - 13, please let us know if you continue to have issues.

**Comment by mileyvirus** [comment]
Still won't work for me unfortunately. Tried each and every one of these java versions:
```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    14.0.1, x86_64:	"OpenJDK 14.0.1"	/Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home
    11.0.2, x86_64:	"OpenJDK 11.0.2"	/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
    1.8.0_131, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home
```

I'm on
```
Darwin iMac.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

**Comment by dkbarn** [comment]
Fixed how? The linked PR shows a number of changes being made in files that are not present in either the 2.1.1 or 2.1.2 releases. Those releases contain an incomplete set of .jar files, and it's unclear how to properly integrate those .jar's into the 2.1.0 release. From what I can tell, 2.1.1 and 2.1.2 are unusable without building from source.
